// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: circt-opt -lower-std-to-handshake %s | FileCheck %s
// CHECK-LABEL:   handshake.func @simple_loop(
// CHECK-SAME:                                %[[VAL_0:.*]]: none, ...) -> none attributes {argNames = ["inCtrl"], resNames = ["outCtrl"]} {
// CHECK:           %[[VAL_1:.*]] = br %[[VAL_0]] : none
// CHECK:           %[[VAL_2:.*]], %[[VAL_3:.*]] = control_merge %[[VAL_1]] : none
// CHECK:           %[[VAL_4:.*]]:2 = fork [2] %[[VAL_2]] : none
// CHECK:           sink %[[VAL_3]] : index
// CHECK:           %[[VAL_5:.*]] = constant %[[VAL_4]]#0 {value = 1 : index} : index
// CHECK:           %[[VAL_6:.*]] = br %[[VAL_4]]#1 : none
// CHECK:           %[[VAL_7:.*]] = br %[[VAL_5]] : index
// CHECK:           %[[VAL_8:.*]], %[[VAL_9:.*]] = control_merge %[[VAL_10:.*]], %[[VAL_6]] : none
// CHECK:           %[[VAL_11:.*]]:2 = fork [2] %[[VAL_8]] : none
// CHECK:           %[[VAL_12:.*]] = mux %[[VAL_9]] {{\[}}%[[VAL_13:.*]], %[[VAL_7]]] : index, index
// CHECK:           %[[VAL_14:.*]]:2 = fork [2] %[[VAL_12]] : index
// CHECK:           %[[VAL_15:.*]] = constant %[[VAL_11]]#0 {value = 42 : index} : index
// CHECK:           %[[VAL_16:.*]] = arith.cmpi slt, %[[VAL_14]]#1, %[[VAL_15]] : index
// CHECK:           %[[VAL_17:.*]]:2 = fork [2] %[[VAL_16]] : i1
// CHECK:           %[[VAL_18:.*]], %[[VAL_19:.*]] = cond_br %[[VAL_17]]#1, %[[VAL_11]]#1 : none
// CHECK:           %[[VAL_20:.*]], %[[VAL_21:.*]] = cond_br %[[VAL_17]]#0, %[[VAL_14]]#0 : index
// CHECK:           sink %[[VAL_21]] : index
// CHECK:           %[[VAL_22:.*]] = merge %[[VAL_20]] : index
// CHECK:           %[[VAL_23:.*]], %[[VAL_24:.*]] = control_merge %[[VAL_18]] : none
// CHECK:           %[[VAL_25:.*]]:2 = fork [2] %[[VAL_23]] : none
// CHECK:           sink %[[VAL_24]] : index
// CHECK:           %[[VAL_26:.*]] = constant %[[VAL_25]]#0 {value = 1 : index} : index
// CHECK:           %[[VAL_27:.*]] = arith.addi %[[VAL_22]], %[[VAL_26]] : index
// CHECK:           %[[VAL_10]] = br %[[VAL_25]]#1 : none
// CHECK:           %[[VAL_13]] = br %[[VAL_27]] : index
// CHECK:           %[[VAL_28:.*]], %[[VAL_29:.*]] = control_merge %[[VAL_19]] : none
// CHECK:           sink %[[VAL_29]] : index
// CHECK:           return %[[VAL_28]] : none
// CHECK:         }
func @simple_loop() {
^bb0:
  br ^bb1
^bb1:	// pred: ^bb0
  %c1 = arith.constant 1 : index
  br ^bb2(%c1 : index)
^bb2(%0: index):	// 2 preds: ^bb1, ^bb3
  %c42 = arith.constant 42 : index
  %1 = arith.cmpi slt, %0, %c42 : index
  cond_br %1, ^bb3, ^bb4
^bb3:	// pred: ^bb2
  %c1_0 = arith.constant 1 : index
  %2 = arith.addi %0, %c1_0 : index
  br ^bb2(%2 : index)
^bb4:	// pred: ^bb2
  return
}
