// NOTE: Assertions have been autogenerated by utils/update_mlir_test_checks.py
// RUN: circt-opt -lower-std-to-handshake %s | FileCheck %s
// CHECK-LABEL:   handshake.func @affine_applies(
// CHECK-SAME:                                   %[[VAL_0:.*]]: none, ...) -> none
// CHECK:           %[[VAL_1:.*]]:18 = fork [18] %[[VAL_0]] : none
// CHECK:           %[[VAL_2:.*]] = constant %[[VAL_1]]#16 {value = 0 : index} : index
// CHECK:           %[[VAL_3:.*]]:2 = fork [2] %[[VAL_2]] : index
// CHECK:           %[[VAL_4:.*]] = constant %[[VAL_1]]#15 {value = 101 : index} : index
// CHECK:           sink %[[VAL_4]] : index
// CHECK:           %[[VAL_5:.*]] = constant %[[VAL_1]]#14 {value = 102 : index} : index
// CHECK:           sink %[[VAL_5]] : index
// CHECK:           %[[VAL_6:.*]] = arith.addi %[[VAL_3]]#0, %[[VAL_3]]#1 : index
// CHECK:           %[[VAL_7:.*]] = constant %[[VAL_1]]#13 {value = 1 : index} : index
// CHECK:           %[[VAL_8:.*]] = arith.addi %[[VAL_6]], %[[VAL_7]] : index
// CHECK:           sink %[[VAL_8]] : index
// CHECK:           %[[VAL_9:.*]] = constant %[[VAL_1]]#12 {value = 103 : index} : index
// CHECK:           %[[VAL_10:.*]] = constant %[[VAL_1]]#11 {value = 104 : index} : index
// CHECK:           %[[VAL_11:.*]] = constant %[[VAL_1]]#10 {value = 105 : index} : index
// CHECK:           %[[VAL_12:.*]] = constant %[[VAL_1]]#9 {value = 106 : index} : index
// CHECK:           %[[VAL_13:.*]] = constant %[[VAL_1]]#8 {value = 107 : index} : index
// CHECK:           %[[VAL_14:.*]] = constant %[[VAL_1]]#7 {value = 108 : index} : index
// CHECK:           %[[VAL_15:.*]] = constant %[[VAL_1]]#6 {value = 109 : index} : index
// CHECK:           %[[VAL_16:.*]] = constant %[[VAL_1]]#5 {value = 2 : index} : index
// CHECK:           %[[VAL_17:.*]] = arith.muli %[[VAL_10]], %[[VAL_16]] : index
// CHECK:           %[[VAL_18:.*]] = arith.addi %[[VAL_9]], %[[VAL_17]] : index
// CHECK:           %[[VAL_19:.*]] = constant %[[VAL_1]]#4 {value = 3 : index} : index
// CHECK:           %[[VAL_20:.*]] = arith.muli %[[VAL_11]], %[[VAL_19]] : index
// CHECK:           %[[VAL_21:.*]] = arith.addi %[[VAL_18]], %[[VAL_20]] : index
// CHECK:           %[[VAL_22:.*]] = constant %[[VAL_1]]#3 {value = 4 : index} : index
// CHECK:           %[[VAL_23:.*]] = arith.muli %[[VAL_12]], %[[VAL_22]] : index
// CHECK:           %[[VAL_24:.*]] = arith.addi %[[VAL_21]], %[[VAL_23]] : index
// CHECK:           %[[VAL_25:.*]] = constant %[[VAL_1]]#2 {value = 5 : index} : index
// CHECK:           %[[VAL_26:.*]] = arith.muli %[[VAL_13]], %[[VAL_25]] : index
// CHECK:           %[[VAL_27:.*]] = arith.addi %[[VAL_24]], %[[VAL_26]] : index
// CHECK:           %[[VAL_28:.*]] = constant %[[VAL_1]]#1 {value = 6 : index} : index
// CHECK:           %[[VAL_29:.*]] = arith.muli %[[VAL_14]], %[[VAL_28]] : index
// CHECK:           %[[VAL_30:.*]] = arith.addi %[[VAL_27]], %[[VAL_29]] : index
// CHECK:           %[[VAL_31:.*]] = constant %[[VAL_1]]#0 {value = 7 : index} : index
// CHECK:           %[[VAL_32:.*]] = arith.muli %[[VAL_15]], %[[VAL_31]] : index
// CHECK:           %[[VAL_33:.*]] = arith.addi %[[VAL_30]], %[[VAL_32]] : index
// CHECK:           sink %[[VAL_33]] : index
// CHECK:           return %[[VAL_1]]#17 : none
// CHECK:         }
func.func @affine_applies() {
    %c0 = arith.constant 0 : index
    %c101 = arith.constant 101 : index
    %c102 = arith.constant 102 : index
    %0 = arith.addi %c0, %c0 : index
    %c1 = arith.constant 1 : index
    %1 = arith.addi %0, %c1 : index
    %c103 = arith.constant 103 : index
    %c104 = arith.constant 104 : index
    %c105 = arith.constant 105 : index
    %c106 = arith.constant 106 : index
    %c107 = arith.constant 107 : index
    %c108 = arith.constant 108 : index
    %c109 = arith.constant 109 : index
    %c2 = arith.constant 2 : index
    %2 = arith.muli %c104, %c2 : index
    %3 = arith.addi %c103, %2 : index
    %c3 = arith.constant 3 : index
    %4 = arith.muli %c105, %c3 : index
    %5 = arith.addi %3, %4 : index
    %c4 = arith.constant 4 : index
    %6 = arith.muli %c106, %c4 : index
    %7 = arith.addi %5, %6 : index
    %c5 = arith.constant 5 : index
    %8 = arith.muli %c107, %c5 : index
    %9 = arith.addi %7, %8 : index
    %c6 = arith.constant 6 : index
    %10 = arith.muli %c108, %c6 : index
    %11 = arith.addi %9, %10 : index
    %c7 = arith.constant 7 : index
    %12 = arith.muli %c109, %c7 : index
    %13 = arith.addi %11, %12 : index
    return
  }
