// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: circt-opt %s --convert-to-llvm | FileCheck %s

// CHECK-LABEL:   llvm.func @convert_eq(
// CHECK-SAME:                          %[[VAL_0:.*]]: i32,
// CHECK-SAME:                          %[[VAL_1:.*]]: i32) -> i1 {
// CHECK:           %[[VAL_2:.*]] = llvm.icmp "eq" %[[VAL_0]], %[[VAL_1]] : i32
// CHECK:           llvm.return %[[VAL_2]] : i1
// CHECK:         }
func @convert_eq(%lhs : i32, %rhs: i32) -> i1 {
    %0 = llhd.eq %lhs, %rhs: i32

    return %0 : i1
}


// CHECK-LABEL:   llvm.func @convert_neq(
// CHECK-SAME:                           %[[VAL_0:.*]]: i32,
// CHECK-SAME:                           %[[VAL_1:.*]]: i32) -> i1 {
// CHECK:           %[[VAL_2:.*]] = llvm.icmp "ne" %[[VAL_0]], %[[VAL_1]] : i32
// CHECK:           llvm.return %[[VAL_2]] : i1
// CHECK:         }
func @convert_neq(%lhs : i32, %rhs: i32) -> i1 {
    %0 = llhd.neq %lhs, %rhs: i32

    return %0 : i1
}
