//===- PIR.td - Property IR dialect definition -------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_PIR_PIR_TD
#define CIRCT_DIALECT_PIR_PIR_TD

include "circt/Dialect/PIR/PIRDialect.td"
include "circt/Dialect/PIR/PIROps.td"

#endif // CIRCT_DIALECT_PIR_PIR_TD
