//===- Server.h - ESI cosim RPC servers -------------------------*- C++ -*-===//
//
// Various classes used to implement the RPC server classes generated by
// CapnProto. Capnp C++ RPC servers are based on 'libkj' and its asynchrony
// model, which is very foreign. This is what the 'kj' namespace is along with
// alternate collections and other utility code.
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_ESI_COSIM_SERVER_H
#define CIRCT_DIALECT_ESI_COSIM_SERVER_H

#include "circt/Dialect/ESI/cosim/Endpoint.h"

namespace std {
class thread;
} // namespace std

namespace circt {
namespace esi {
namespace cosim {

/// The main RpcServer. Does not implement any capnp RPC interfaces but contains
/// the capnp main RPC server. We run the capnp server in its own thread to be
/// more responsive to network traffic and so as to not slow down the
/// simulation.
class RpcServer {
public:
  EndpointRegistry endpoints;

  RpcServer();
  ~RpcServer();

  /// Start and stop the server thread.
  void run(uint16_t port);
  void stop();

private:
  using Lock = std::lock_guard<std::mutex>;

  /// The thread's main loop function. Exits on shutdown.
  void mainLoop(uint16_t port);

  std::thread *mainThread;
  volatile bool stopSig;
  std::mutex m;
};

} // namespace cosim
} // namespace esi
} // namespace circt

#endif
