//===----------------------------------------------------------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_LLHD_IR_LLHDOPS_TD
#define CIRCT_DIALECT_LLHD_IR_LLHDOPS_TD

include "circt/Dialect/LLHD/IR/LLHDValueOps.td"
include "circt/Dialect/LLHD/IR/LLHDSignalOps.td"
include "circt/Dialect/LLHD/IR/LLHDExtractOps.td"
include "circt/Dialect/LLHD/IR/LLHDStructureOps.td"

#endif // CIRCT_DIALECT_LLHD_IR_LLHDOPS_TD
