//===- Handshake.td - Handshake dialect definition ---------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This is the top level file for the Handshake dialect.
//
//===----------------------------------------------------------------------===//

#ifndef HANDSHAKE_TD
#define HANDSHAKE_TD

include "circt/Dialect/Handshake/HandshakeDialect.td"
include "circt/Dialect/Handshake/HandshakeOps.td"

#endif // HANDSHAKE_TD
