//===-- HWOps.td - Entry point for HWOps bindings ----------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef BINDINGS_PYTHON_LTL_OPS
#define BINDINGS_PYTHON_LTL_OPS

include "circt/Dialect/LTL/LTLOps.td"

#endif
