//===- PipelineOps.td - Entry point for Pipeline bindings --*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//

#ifndef BINDINGS_PYTHON_PIPELINE_OPS
#define BINDINGS_PYTHON_PIPELINE_OPS

include "circt/Dialect/Pipeline/Pipeline.td"

#endif
