// REQUIRES: hsdbg
// RUN: hsdbg --print-bundles-only %S/resolve_bundles.dot %S/resolve_bundles.vcd

// CHECK: "TOP.exponent.in0" -> "TOP.exponent.handshake_fork0"// input="in0"
// CHECK: "TOP.exponent.in1" -> "TOP.exponent.handshake_mux4"// input="in1"
// CHECK: "TOP.exponent.inCtrl" -> "TOP.exponent.handshake_fork1" [style="dashed" ]// input="in0"
// CHECK: "TOP.exponent.handshake_cond_br4" -> "TOP.exponent.out0"// input="in0" output="outFalse"
// CHECK: "TOP.exponent.handshake_cond_br3" -> "TOP.exponent.outCtrl" [style="dashed" ]// input="in1" output="outFalse"
// CHECK: "TOP.exponent.arith_addi0" -> "TOP.exponent.handshake_buffer7"// input="in0" output="out0"
// CHECK: "TOP.exponent.arith_cmpi0" -> "TOP.exponent.handshake_fork5"// input="in0" output="out0"
// CHECK: "TOP.exponent.arith_muli0" -> "TOP.exponent.handshake_mux3"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_buffer0" -> "TOP.exponent.arith_cmpi0"// input="in1" output="out0"
// CHECK: "TOP.exponent.handshake_buffer1" -> "TOP.exponent.handshake_cond_br3" [style="dashed" ]// output="out0" input="data"
// CHECK: "TOP.exponent.handshake_buffer2" -> "TOP.exponent.handshake_mux4" [style="dashed" ]// input="select" output="out0"
// CHECK: "TOP.exponent.handshake_buffer3" -> "TOP.exponent.handshake_mux0"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_buffer4" -> "TOP.exponent.arith_muli0"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_buffer5" -> "TOP.exponent.handshake_mux1"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_buffer6" -> "TOP.exponent.handshake_mux2"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_buffer7" -> "TOP.exponent.handshake_mux4"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_cond_br0" -> "TOP.exponent.handshake_sink0"// input="in0" output="outFalse"
// CHECK: "TOP.exponent.handshake_cond_br0" -> "TOP.exponent.handshake_buffer3"// input="in0" output="outTrue"
// CHECK: "TOP.exponent.handshake_cond_br1" -> "TOP.exponent.handshake_sink1"// input="in0" output="outFalse"
// CHECK: "TOP.exponent.handshake_cond_br1" -> "TOP.exponent.handshake_fork6"// input="in0" output="outTrue"
// CHECK: "TOP.exponent.handshake_cond_br2" -> "TOP.exponent.handshake_sink2"// input="in0" output="outFalse"
// CHECK: "TOP.exponent.handshake_cond_br2" -> "TOP.exponent.handshake_fork7"// input="in0" output="outTrue"
// CHECK: "TOP.exponent.handshake_cond_br3" -> "TOP.exponent.outCtrl" [style="dashed" ]// input="in1" output="outFalse"
// CHECK: "TOP.exponent.handshake_cond_br3" -> "TOP.exponent.handshake_control_merge0" [style="dashed" ]// input="in0" output="outTrue"
// CHECK: "TOP.exponent.handshake_cond_br4" -> "TOP.exponent.out0"// input="in0" output="outFalse"
// CHECK: "TOP.exponent.handshake_cond_br4" -> "TOP.exponent.handshake_buffer4"// input="in0" output="outTrue"
// CHECK: "TOP.exponent.handshake_cond_br5" -> "TOP.exponent.handshake_sink3"// input="in0" output="outFalse"
// CHECK: "TOP.exponent.handshake_cond_br5" -> "TOP.exponent.arith_addi0"// input="in0" output="outTrue"
// CHECK: "TOP.exponent.handshake_constant0" -> "TOP.exponent.handshake_mux2"// input="in1" output="out0"
// CHECK: "TOP.exponent.handshake_constant1" -> "TOP.exponent.handshake_mux0"// input="in1" output="out0"
// CHECK: "TOP.exponent.handshake_control_merge0" -> "TOP.exponent.handshake_buffer1" [style="dashed" ]// input="in0" output="dataOut"
// CHECK: "TOP.exponent.handshake_control_merge0" -> "TOP.exponent.handshake_fork3" [style="dashed" ]// input="in0" output="index"
// CHECK: "TOP.exponent.handshake_fork0" -> "TOP.exponent.handshake_mux1"// input="in1" output="out0"
// CHECK: "TOP.exponent.handshake_fork0" -> "TOP.exponent.handshake_mux3"// input="in1" output="out1"
// CHECK: "TOP.exponent.handshake_fork1" -> "TOP.exponent.handshake_constant1" [style="dashed" ]// input="ctrl" output="out0"
// CHECK: "TOP.exponent.handshake_fork1" -> "TOP.exponent.handshake_constant0" [style="dashed" ]// input="ctrl" output="out1"
// CHECK: "TOP.exponent.handshake_fork1" -> "TOP.exponent.handshake_control_merge0" [style="dashed" ]// input="in1" output="out2"
// CHECK: "TOP.exponent.handshake_fork2" -> "TOP.exponent.handshake_cond_br0"// output="out0" input="data"
// CHECK: "TOP.exponent.handshake_fork2" -> "TOP.exponent.handshake_buffer0"// input="in0" output="out1"
// CHECK: "TOP.exponent.handshake_fork3" -> "TOP.exponent.handshake_buffer2"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_fork3" -> "TOP.exponent.handshake_mux3" [style="dashed" ]// output="out1" input="select"
// CHECK: "TOP.exponent.handshake_fork3" -> "TOP.exponent.handshake_mux2" [style="dashed" ]// output="out2" input="select"
// CHECK: "TOP.exponent.handshake_fork3" -> "TOP.exponent.handshake_mux1" [style="dashed" ]// input="select" output="out3"
// CHECK: "TOP.exponent.handshake_fork3" -> "TOP.exponent.handshake_mux0" [style="dashed" ]// output="out4" input="select"
// CHECK: "TOP.exponent.handshake_fork4" -> "TOP.exponent.handshake_cond_br5"// output="out0" input="data"
// CHECK: "TOP.exponent.handshake_fork4" -> "TOP.exponent.arith_cmpi0"// input="in0" output="out1"
// CHECK: "TOP.exponent.handshake_fork5" -> "TOP.exponent.handshake_cond_br5" [style="dashed" ]// input="cond" output="out0"
// CHECK: "TOP.exponent.handshake_fork5" -> "TOP.exponent.handshake_cond_br4" [style="dashed" ]// output="out1" input="cond"
// CHECK: "TOP.exponent.handshake_fork5" -> "TOP.exponent.handshake_cond_br3" [style="dashed" ]// output="out2" input="cond"
// CHECK: "TOP.exponent.handshake_fork5" -> "TOP.exponent.handshake_cond_br2" [style="dashed" ]// input="cond" output="out3"
// CHECK: "TOP.exponent.handshake_fork5" -> "TOP.exponent.handshake_cond_br1" [style="dashed" ]// output="out4" input="cond"
// CHECK: "TOP.exponent.handshake_fork5" -> "TOP.exponent.handshake_cond_br0" [style="dashed" ]// output="out5" input="cond"
// CHECK: "TOP.exponent.handshake_fork6" -> "TOP.exponent.handshake_buffer5"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_fork6" -> "TOP.exponent.arith_muli0"// input="in1" output="out1"
// CHECK: "TOP.exponent.handshake_fork7" -> "TOP.exponent.handshake_buffer6"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_fork7" -> "TOP.exponent.arith_addi0"// input="in1" output="out1"
// CHECK: "TOP.exponent.handshake_mux0" -> "TOP.exponent.handshake_fork2"// input="in0" output="out0"
// CHECK: "TOP.exponent.handshake_mux1" -> "TOP.exponent.handshake_cond_br1"// output="out0" input="data"
// CHECK: "TOP.exponent.handshake_mux2" -> "TOP.exponent.handshake_cond_br2"// output="out0" input="data"
// CHECK: "TOP.exponent.handshake_mux3" -> "TOP.exponent.handshake_cond_br4"// output="out0" input="data"
// CHECK: "TOP.exponent.handshake_mux4" -> "TOP.exponent.handshake_fork4"// input="in0" output="out0"
