//===- Calyx.td - Calyx dialect definition -----------------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This is the top level file for the Calyx dialect.
//
//===----------------------------------------------------------------------===//

#ifndef CALYX_TD
#define CALYX_TD

include "circt/Dialect/Calyx/CalyxDialect.td"
include "circt/Dialect/Calyx/CalyxStructure.td"
include "circt/Dialect/Calyx/CalyxControl.td"
include "circt/Dialect/Calyx/CalyxPrimitives.td"

#endif // CALYX_TD
