// RUN: circt-opt --arc-lower-sim-to-arcs %s | FileCheck %s

sim.func.dpi @foo(out arg0: i32, in %arg1: i32, out arg2: i32)
// CHECK-LABEL:  func.func private @foo(!llvm.ptr, i32, !llvm.ptr)
// CHECK-LABEL:  arc.define @foo_dpi_arc(%arg0: i32) -> (i32, i32) {
// CHECK-NEXT:    %0 = llvm.mlir.constant(1 : i64) : i64
// CHECK-NEXT:    %1 = llvm.alloca %0 x i32 : (i64) -> !llvm.ptr
// CHECK-NEXT:    %2 = llvm.mlir.constant(1 : i64) : i64
// CHECK-NEXT:    %3 = llvm.alloca %2 x i32 : (i64) -> !llvm.ptr
// CHECK-NEXT:    func.call @foo(%1, %arg0, %3) : (!llvm.ptr, i32, !llvm.ptr) -> ()
// CHECK-NEXT:    %4 = llvm.load %1 : !llvm.ptr -> i32
// CHECK-NEXT:    %5 = llvm.load %3 : !llvm.ptr -> i32
// CHECK-NEXT:    arc.output %4, %5 : i32, i32
// CHECK-NEXT:   }

// CHECK-LABEL: hw.module @dpi_call
hw.module @dpi_call(in %clock : !seq.clock, in %enable : i1, in %in: i32,
          out o1: i32, out o2: i32, out o3: i32, out o4: i32, out o5: i32, out o6: i32) {
  // CHECK-NEXT: %[[RESULT1:.+]]:2 = arc.state @foo_dpi_arc(%in) clock %clock enable %enable latency 1 : (i32) -> (i32, i32)
  // CHECK-NEXT: %[[RESULT2:.+]]:2 = arc.state @foo_dpi_arc(%in) clock %clock latency 1 : (i32) -> (i32, i32)
  // CHECK-NEXT: %[[RESULT3:.+]]:2 = arc.call @foo_dpi_arc(%in) : (i32) -> (i32, i32)
  // hw.output %0#0, %0#1, %1#0, %1#1, %2#0, %2#1 : i32, i32, i32, i32, i32, i32 
  %0, %1 = sim.func.dpi.call @foo(%in) clock %clock enable %enable: (i32) -> (i32, i32)
  %2, %3 = sim.func.dpi.call @foo(%in) clock %clock : (i32) -> (i32, i32)
  %4, %5 = sim.func.dpi.call @foo(%in) : (i32) -> (i32, i32)
  hw.output %0, %1, %2, %3, %4, %5 : i32, i32, i32, i32, i32, i32
}