// RUN: circt-opt %s --synth-functional-reduction=test-transformation | FileCheck %s

// AND(AND(a, not b), AND(c, not d)) is equivalent to AND(a, not b, c, not d).
// CHECK-LABEL: hw.module @test_mixed
hw.module @test_mixed(in %a: i1, in %b: i1, in %c: i1, in %d: i1, out out1: i1, out out2: i1, out out3: i1) {
  // CHECK: %[[RESULT_0:.+]] = synth.aig.and_inv %a, not %b
  // CHECK: %[[RESULT_1:.+]] = synth.aig.and_inv %c, not %d
  // CHECK: %[[RESULT_2:.+]] = synth.aig.and_inv %[[RESULT_0]], %[[RESULT_1]]
  // CHECK: %[[RESULT_3:.+]] = synth.aig.and_inv %a, not %b, %c, not %d
  // CHECK-NEXT: %[[CHOICE:.+]] = synth.choice %[[RESULT_2]], %[[RESULT_3]]
  // CHECK: %[[RESULT_4:.+]] = synth.aig.and_inv %a, not %b, not %c, not %d
  // CHECK-NEXT: hw.output %[[CHOICE]], %[[CHOICE]], %[[RESULT_4]]
  %0 = synth.aig.and_inv %a, not %b : i1
  %1 = synth.aig.and_inv %c, not %d : i1
  %2 = synth.aig.and_inv %0, %1 {synth.test.fc_equiv_class = 0} : i1
  %3 = synth.aig.and_inv %a, not %b, %c, not %d {synth.test.fc_equiv_class = 0} : i1
  %4 = synth.aig.and_inv %a, not %b, not %c, not %d {synth.test.fc_equiv_class = 1} : i1
  hw.output %2, %3, %4 : i1, i1, i1
}

// CHECK-LABEL: hw.module @test_supported_ops
hw.module @test_supported_ops(in %a: i1, in %b: i1, in %c: i1,
                              out out0: i1, out out1: i1,
                              out out2: i1, out out3: i1,
                              out out4: i1, out out5: i1) {
  // CHECK: %[[OR0:.+]] = comb.or %a, %b, %c
  // CHECK: %[[OR1:.+]] = comb.or %c, %b, %a
  // CHECK-NEXT: %[[ORCHOICE:.+]] = synth.choice %[[OR0]], %[[OR1]] : i1
  // CHECK: %[[XOR0:.+]] = comb.xor %a, %b
  // CHECK: %[[XOR1:.+]] = comb.xor %b, %a
  // CHECK-NEXT: %[[XORCHOICE:.+]] = synth.choice %[[XOR0]], %[[XOR1]] : i1
  // CHECK: %[[AND0:.+]] = comb.and %a, %b
  // CHECK: %[[AND1:.+]] = comb.and %b, %a
  // CHECK-NEXT: %[[ANDCHOICE:.+]] = synth.choice %[[AND0]], %[[AND1]] : i1
  // CHECK: hw.output %[[ORCHOICE]], %[[ORCHOICE]], %[[XORCHOICE]], %[[XORCHOICE]], %[[ANDCHOICE]], %[[ANDCHOICE]] : i1, i1, i1, i1, i1, i1
  %0 = comb.or %a, %b, %c {synth.test.fc_equiv_class = 2} : i1
  %1 = comb.or %c, %b, %a {synth.test.fc_equiv_class = 2} : i1
  %2 = comb.xor %a, %b {synth.test.fc_equiv_class = 4} : i1
  %3 = comb.xor %b, %a {synth.test.fc_equiv_class = 4} : i1
  %4 = comb.and %a, %b {synth.test.fc_equiv_class = 5} : i1
  %5 = comb.and %b, %a {synth.test.fc_equiv_class = 5} : i1
  hw.output %0, %1, %2, %3, %4, %5 : i1, i1, i1, i1, i1, i1
}

// CHECK-LABEL: hw.module @test_inversion_equiv
hw.module @test_inversion_equiv(in %a: i1, in %b: i1, out out0: i1, out out1: i1) {
  // CHECK: %[[AND:.+]] = synth.aig.and_inv not %a, not %b
  // CHECK: %[[OR:.+]] = comb.or %a, %b
  // CHECK: %[[NOTMEMBER:.+]] = synth.aig.and_inv not %[[OR]]
  // CHECK: %[[CHOICE:.+]] = synth.choice %[[AND]], %[[NOTMEMBER]] : i1
  // CHECK: %[[CHOICENOT:.+]] = synth.aig.and_inv not %[[CHOICE]]
  // CHECK: hw.output %[[CHOICE]], %[[CHOICENOT]]
  %0 = synth.aig.and_inv not %a, not %b {synth.test.fc_equiv_class = 10} : i1
  %1 = comb.or %a, %b {synth.test.fc_equiv_class = 10} : i1
  hw.output %0, %1 : i1, i1
}

// CHECK-LABEL: hw.module @test_no_ssa_cycle
hw.module @test_no_ssa_cycle(in %a: i1, in %b: i1,
                             out out0: i1, out out1: i1, out out2: i1, out out3: i1) {
// CHECK: %[[AB:.+]] = synth.aig.and_inv %a, %b
// CHECK: %[[BA:.+]] = synth.aig.and_inv %b, %a
// CHECK: %[[CHOICE:.+]] = synth.choice %[[AB]], %[[BA]]
// CHECK: %[[TEST:.+]] = synth.aig.and_inv not %[[CHOICE]], not %[[CHOICE]]
// CHECK: hw.output %[[CHOICE]], %[[CHOICE]], %[[TEST]], %[[CHOICE]]
  %ab = synth.aig.and_inv %a, %b {synth.test.fc_equiv_class = 7} : i1
  %aba = synth.aig.and_inv %ab, %a {synth.test.fc_equiv_class = 7} : i1
  %test = synth.aig.and_inv not %ab, not %aba {synth.test.fc_equiv_class = 8} : i1
  %ba = synth.aig.and_inv %b, %a {synth.test.fc_equiv_class = 7} : i1
  hw.output %ab, %aba, %test, %ba : i1, i1, i1, i1
}

// CHECK-LABEL: hw.module @test_xor_inv_equiv
hw.module @test_xor_inv_equiv(in %a: i1, in %b: i1, out out0: i1, out out1: i1) {
  // CHECK: %[[XOR_INV:.+]] = synth.xor_inv %a, %b
  // CHECK: %[[XOR:.+]] = comb.xor %b, %a
  // CHECK: %[[CHOICE:.+]] = synth.choice %[[XOR_INV]], %[[XOR]] : i1
  // CHECK: hw.output %[[CHOICE]], %[[CHOICE]] : i1, i1
  %0 = synth.xor_inv %a, %b {synth.test.fc_equiv_class = 11} : i1
  %1 = comb.xor %b, %a {synth.test.fc_equiv_class = 11} : i1
  hw.output %0, %1 : i1, i1
}

// CHECK-LABEL: hw.module @test_reachable_erased
hw.module @test_reachable_erased(in %a: i1, in %b: i1, out out0: i1, out out1: i1) {
  // CHECK: %[[AB:.+]] = synth.aig.and_inv %a, %b
  // CHECK: %[[BA:.+]] = synth.aig.and_inv %b, %a
  // CHECK: %[[CHOICE:.+]] = synth.choice %[[AB]], %[[BA]]
  // CHECK-NOT: synth.aig.and_inv %[[CHOICE]], %a
  // CHECK: hw.output %[[CHOICE]], %[[CHOICE]]
  %ab  = synth.aig.and_inv %a, %b {synth.test.fc_equiv_class = 7} : i1
  %aba = synth.aig.and_inv %ab, %a {synth.test.fc_equiv_class = 7} : i1
  %ba  = synth.aig.and_inv %b, %a {synth.test.fc_equiv_class = 7} : i1
  hw.output %ab, %aba : i1, i1
}

// CHECK-LABEL: hw.module @test_mux_inv_equiv
hw.module @test_mux_inv_equiv(in %c: i1, in %a: i1, in %b: i1, out out0: i1, out out1: i1) {
  // CHECK: %[[MUX:.+]] = synth.mux_inv %c, %a, %b
  // CHECK: %[[CA:.+]] = synth.aig.and_inv %c, %a
  // CHECK: %[[CB:.+]] = synth.aig.and_inv not %c, %b
  // CHECK: %[[OR:.+]] = synth.aig.and_inv not %[[CA]], not %[[CB]]
  // CHECK: %[[RESULT:.+]] = synth.aig.and_inv not %[[OR]]
  // CHECK: %[[CHOICE:.+]] = synth.choice %[[MUX]], %[[RESULT]] : i1
  // CHECK: hw.output %[[CHOICE]], %[[CHOICE]] : i1, i1
  %0 = synth.mux_inv %c, %a, %b {synth.test.fc_equiv_class = 12} : i1
  %1 = synth.aig.and_inv %c, %a : i1
  %2 = synth.aig.and_inv not %c, %b : i1
  %3 = synth.aig.and_inv not %1, not %2 : i1
  %4 = synth.aig.and_inv not %3 {synth.test.fc_equiv_class = 12} : i1
  hw.output %0, %4 : i1, i1
}


