// Generated by CIRCT e9c9b2dca
`ifndef __PYCDE_TYPES__
`define __PYCDE_TYPES__
`ifndef _TYPESCOPE_pycde
`define _TYPESCOPE_pycde
  typedef struct packed {logic [31:0] data; logic [1:0] resp; } AXI_Lite_Read_Resp;
  typedef struct packed {logic write; logic upper; } MMIOSel;
  typedef
    struct packed {logic upper; logic write; logic [31:0] offset; logic [63:0] data; }
    MMIOIntermediateCmd;
`endif // _TYPESCOPE_pycde
`endif // __PYCDE_TYPES__
module Dummy();	// {/workspace/circt/build/default/tools/circt/python_packages/pycde/pycde/module.py:491 <- /workspace/circt/lib/Dialect/ESI/runtime/tests/integration/hw/esi_ram.py:26}
endmodule

