//===- GAAAttributes.td - GAA Dialect Attributes -----------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file contains the GAA dialect custom attributes.
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_GAA_GAAATTRIBUTES_TD
#define CIRCT_DIALECT_GAA_GAAATTRIBUTES_TD

#endif // CIRCT_DIALECT_GAA_GAAATTRIBUTES_TD
