//===- DCCanonicalization.td - DC canonicalization ---------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Canonicalization patterns for the DC dialect.
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_DC_DCCANONICALIZATION_TD
#define CIRCT_DIALECT_DC_DCCANONICALIZATION_TD

include "circt/Dialect/DC/DC.td"
include "mlir/IR/PatternBase.td"


#endif // CIRCT_DIALECT_DC_DCCANONICALIZATION_TD
