//===- HWArithOps.cpp - Implement the HW arithmetic operations ------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implement the HW arithmetic ops.
//
//===----------------------------------------------------------------------===//

#include "circt/Dialect/HWArith/HWArithOps.h"
#include "mlir/IR/Builders.h"

using namespace circt;
using namespace hwarith;

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "circt/Dialect/HWArith/HWArith.cpp.inc"
