//===- OFIRAttributes.td - FIRRTL Types Definition ---------*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Definitions of FIRRTL attributes.
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_OFIR_OFIRATTRIBUTES_TD
#define CIRCT_DIALECT_OFIR_OFIRATTRIBUTES_TD

include "mlir/IR/EnumAttr.td"

#endif // CIRCT_DIALECT_OFIR_OFIRATTRIBUTES_TD
