//===- OFIRCanonicalization.td - OFIR canonicalization -*- tablegen -----*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// The canonicalization patterns for the OFIR dialect.
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_OFIR_OFIRCANONICALIZATION_TD
#define CIRCT_DIALECT_OFIR_OFIRCANONICALIZATION_TD

include "circt/Dialect/OFIR/OFIR.td"

#endif // CIRCT_DIALECT_OFIR_OFIRCANONICALIZATION_TD
