name: Cleanup Cache

on:
  workflow_call:
    inputs:
      cache_key_pattern:
        description: "Cache key pattern to clean up"
        required: true
        type: string

jobs:
  cleanup-cache:
    name: Cleanup Cache
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - name: Get CIRCT
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          submodules: "false"

      - name: Set git safe
        run: |
          git config --global --add safe.directory $PWD

      - name: Check cache and remove
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ./utils/cleanup-cache.sh \
            --pattern "${{ inputs.cache_key_pattern }}" \
            --ref "${{ github.ref }}"
