name: Nightly integration tests

# Run on request and every day at 12 noon UTC
on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *

jobs:
  build-circt:
    name: "${{ matrix.compiler }}/${{ matrix.build-type }}/${{ matrix.build-shared == 'ON' && 'shared' || 'static' }}-libs/asserts-${{ matrix.build-assert == 'ON' && 'on' || 'off' }}${{ matrix.valgrind && '/valgrind' || '' }}"
    strategy:
      fail-fast: false
      matrix:
        build-assert: [ON, OFF]
        build-shared: [ON, OFF]
        build-type: [Debug, Release]
        compiler:
          - clang
          - gcc
          - clang-19
        valgrind: [false, true]
        exclude:
          - build-type: Debug
            valgrind: true
          - build-type: Release
            valgrind: true
            build-assert: OFF
          - build-type: Release
            valgrind: true
            build-shared: ON
          # TODO: This corner is failing and has been for some time. #5253.
          - build-type: Release
            compiler: gcc
            valgrind: true
          # clang-19 is used for valgrind builds instead of clang.
          - compiler: clang-19
            valgrind: false
          - compiler: clang
            valgrind: true
    permissions:
      contents: write
      actions: write
    uses: ./.github/workflows/unifiedBuildTestAndInstall.yml
    with:
      runner: ubuntu-24.04
      cmake_build_type: ${{ matrix.build-type }}
      build_shared_libs: ${{ matrix.build-shared }}
      llvm_enable_assertions: ${{ matrix.build-assert }}
      run_tests: true
      run_integration_tests: true
      install_target: ""
      package_name_prefix: ""
      cmake_c_compiler: ${{ matrix.compiler }}
      valgrind: ${{ matrix.valgrind }}
